name: Test driver postgres
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.22" ]
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test driver postgres
        working-directory: ./driver/postgres
        run: |
          go mod tidy
          go test -v -coverprofile=coverage.out ./...
      - name: Upload driver postgres coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./driver/postgres/coverage.out
          fail_ci_if_error: true
          verbose: true
          flags: postgres
          codecov_yml_path: ./.codecov.yml

